// Official FastForward MV3 match hosts (src/bypasses/*.js)
// plus the public docs/Bypassed.md list. Deduped, lowercase, no scheme.
export const SUPPORTED = [
  "1link.club",
  "4shared.com",
  "5play.ru",
  "acortalink.me",
  "admaven.com",
  "adtival.network",
  "akoam.net",
  "akoam.to",
  "akwam.org",
  "an1.com",
  "androidtop.net",
  "anonym.ninja",
  "apkhubs.com",
  "bc.vc",
  "bcvc.live",
  "blitly.io",
  "bluemediafile.site",
  "bluemediafiles.com",
  "boost.ink",
  "brpaper.com",
  "bst.gg",
  "cb.click",
  "cb.run",
  "cheatsquad.gg",
  "clictune.com",
  "complete2unlock.com",
  "cpmlink.net",
  "crackedappsstore.com",
  "curseforge.com",
  "daominhha.com",
  "earnme.club",
  "enlacito.com",
  "favpng.com",
  "fc-lc.com",
  "filedm.com",
  "filefactory.com",
  "filehorse.com",
  "filepuma.com",
  "firefaucet.win",
  "forex1pro.com",
  "fssquad.com",
  "gamesmega.net",
  "getwallpapers.com",
  "gixen.com",
  "idnation.net",
  "indishare.org",
  "leitup.com",
  "letsboost.net",
  "liblink.pl",
  "linegee.net",
  "link-to.net",
  "links.shortenbuddy.com",
  "linkspy.cc",
  "linkvertise.com",
  "linkvertise.net",
  "lkc21.net",
  "lnk.news",
  "lnk2.cc",
  "longfiles.com",
  "loot-link.com",
  "loot-links.com",
  "lootlinks.co",
  "mboost.me",
  "mydramalist.com",
  "oko.sh",
  "onepieceex.net",
  "online-fix.me",
  "ouo.io",
  "ouo.press",
  "oxy.cloud",
  "pcgamestorrents.org",
  "pirateproxy.wtf",
  "portableapps.com",
  "rekonise.com",
  "ryn.cc",
  "sfile.mobi",
  "shortly.xyz",
  "shortmoz.link",
  "softpedia.com",
  "sourceforge.net",
  "spaste.com",
  "srt.am",
  "sub2unlock.com",
  "sub4unlock.com",
  "syosetu.org",
  "tik.lat",
  "tl.gd",
  "uiz.app",
  "uiz.io",
  "uploadking.net",
  "uploadrar.com",
  "uploadrar.net",
  "ux9.de",
  "wadooo.com",
  "work.click",
  "work.ink",
  "ytsubme.com",
  "boostme.gg",
  "ay.link",
  "aylink.co",
  "sh.st",
  "clkmein.com",
  "viid.me",
  "gestyy.com",
  "destyy.com",
  "ceesty.com",
  "adshrink.it",
  "tinyurl.is",
  "shorten.sh",
  "pahe.in",
  "pahe.ph",
  "pahe.me",
  "binbox.io",
  "cuty.io",
  "bit.ly",
  "tinyurl.com",
  "is.gd",
  "t.co",
  "goo.gl"
];

export const FF_MODULES = [
  { file: "linkvertise.js", hosts: ["linkvertise.com", "linkvertise.net", "link-to.net"] },
  { file: "boost.js", hosts: ["boost.ink"] },
  { file: "rekonise.js", hosts: ["rekonise.com"] },
  { file: "sub2unlock.js", hosts: ["sub2unlock.com"] },
  { file: "sub4unlock.js", hosts: ["sub4unlock.com"] },
  { file: "letsboost.js", hosts: ["letsboost.net"] },
  { file: "ytsubme.js", hosts: ["ytsubme.com"] },
  { file: "workink.js", hosts: ["work.ink"] },
  { file: "ouo.js", hosts: ["ouo.io", "ouo.press"] },
  { file: "lootlink.js", hosts: ["lootlinks.co", "loot-links.com", "loot-link.com"] }
];

export function hostnameOf(url) {
  try {
    return new URL(url).hostname.replace(/^www\./, "").toLowerCase();
  } catch {
    return "";
  }
}

export function isSupportedHost(urlOrHost) {
  const host = urlOrHost.includes("://") ? hostnameOf(urlOrHost) : urlOrHost.replace(/^www\./, "").toLowerCase();
  if (!host) return false;
  return SUPPORTED.some((d) => host === d || host.endsWith(`.${d}`));
}

export function filterSupported(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return [...SUPPORTED].sort();
  return SUPPORTED.filter((d) => d.includes(q)).sort();
}
